name: SonarCloud
on:
  push:
    branches: ["main", "submission/**", "feature/**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: xdebug
          tools: composer

      - name: Install backend deps + tests
        working-directory: backend
        run: |
          composer install --no-interaction --prefer-dist --no-progress
          mkdir -p build/logs
          if [ -x ./vendor/bin/phpunit ]; then ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml || true; fi

      - uses: actions/setup-java@v4
        with: { distribution: "temurin", java-version: "17" }

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: "-X" # enable debug logging once
        with:
         args: >
         -Dsonar.organization=samshingenge
         -Dsonar.projectKey=Samshingenge_gondwana-rates-api
  # make sure this secret exists
